Traceback (most recent call last):
  File "/opt/jupyterhub/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/jupyterhub/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Constants
rho = 1000 * 1e-09  # kg/mm^3
g = 9.81 * 1000     # mm/s^2
diameter = 10       # mm  nozzle diameter
s = 35              # mm distance between nozzle-vane
Mass = 600/1000    # (kg) the jockey mass
a = 150             # mm vane-pivot distance

# Data for the flat plate
# Group 4
y1 = np.array([102, 86, 68, 42, 19])  # mm
vol1 = np.array([2000, 2000, 2000, 2000, 2000])  # mL
t1 = np.array([[3.45, 3.31, 3.25],
                [3.93, 3.71, 3.74],
                [4.37, 4.36, 4.33],
                [5.21, 5.25, 5.20],
                [6.88, 6.90, 6.78]])  # seconds

# Data for the hemispherical cup
y2 = np.array([188, 140, 90, 50, 20])  
vol2 = np.array([2000, 2000, 2000, 2000, 2000])
t2 = np.array([[3.53, 3.55, 3.66],
                [3.78, 3.98, 4.18],
                [4.98, 4.75, 4.93],
                [6.68, 6.25, 6.58],
                [9.49, 9.36, 9.54]])

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlinear_model[39;00m [38;5;28;01mimport[39;00m LinearRegression
[1;32m      6[0m [38;5;66;03m# Constants[39;00m
[1;32m      7[0m rho [38;5;241m=[39m [38;5;241m1000[39m [38;5;241m*[39m [38;5;241m1e-09[39m  [38;5;66;03m# kg/mm^3[39;00m

[0;31mModuleNotFoundError[0m: No module named 'sklearn'

